name: Deploy Portfolio to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-app:latest

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOSTNAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "$PRIVATE_KEY" | base64 -d > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-app:latest
          docker stop portfolio-app || true
          docker rm portfolio-app || true
          docker run -d \
            -p 80:80 \
            --name portfolio-app \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-app:latest
          docker image prune -af
        EOF
